### ISSUE TITLE
material-ui 0.15.0 

### ISSUE THREAD

**Issue by FredericHeem** [codefoundries/material-ui-country-flags#4]
The new material-ui version 0.15.0  has a breaking change on how to import components. See the [release note](https://github.com/callemall/material-ui/releases) for more details.

**Comment by thelordoftheboards** [comment]
Thank you very much. I will look to update this soon before the new version becomes released.

**Comment by thelordoftheboards** [comment]
Apparently simply adding .default breaks it for material-ui 0.14

**Comment by thelordoftheboards** [comment]
version 2 should resolve this issue. I moved everything over to Babel and I'm now using ES6 imports and export statements. Works great with MUI 0.14 and from what I gather should still work with 0.15.
